---
- name: reload systemd
  systemd:
    daemon_reload: true
  become: true
  listen: "reload systemd"

- name: restart node_exporter
  systemd:
    name: node_exporter
    state: restarted
  become: true
  listen: "restart node_exporter"

- name: verify node_exporter
  block:
    - name: Wait for service to stabilize
      pause:
        seconds: 3

    - name: Check service is active after changes
      systemd:
        name: node_exporter
      register: handler_service_status
      failed_when: handler_service_status.status.ActiveState != "active"

    - name: Verify port is listening after restart
      wait_for:
        port: "{{ node_exporter_port }}"
        host: "127.0.0.1"
        timeout: 30

    - name: Test metrics endpoint from handler
      uri:
        url: "http://localhost:{{ node_exporter_port }}/metrics"
        method: GET
        status_code: 200
        timeout: 10
      retries: 3
      delay: 5

    - name: Log successful verification
      debug:
        msg: "✅ Node Exporter service verified successfully after changes"

  become: true
  listen: "verify node_exporter"